update: clean up main branch
notaryproject/notation-go pull request #172
Opened 2022-10-19 06:59 UTC by patrickzheng200

1. Deprecated the old verification workflow.
2. Removed usage of cache.

Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

2022-10-19 13:31 UTC, shizhMSFT approved these changes
LGTM

2022-10-19 13:31 UTC, shizhMSFT commented on go.mod
> +go 1.19
The golang version should not be bumped up.

2022-10-19 13:32 UTC, shizhMSFT requested changes
Let's revert the go version bump up in the `go.mod` before merging.

2022-10-19 17:38 UTC, rgnote approved these changes

2022-10-20 02:32 UTC, shizhMSFT approved these changes
LGTM

2022-10-20 02:33 UTC, merged