github release template workflow
notaryproject/notation-go pull request #65
Opened 2022-06-24 00:26 UTC by dtzar

Add the github action workflow to help automate releases

2022-06-24 23:45 UTC, gokarnm approved these changes

2022-06-24 23:45 UTC, gokarnm commented
Needs one more review to merge. cc: @shizhMSFT

2022-06-25 06:58 UTC, shizhMSFT requested changes
Go releaser is used for releasing binaries from go sources. Also, goreleaser requires a config file `.goreleaser.yml` to do release. For instance, https://github.com/notaryproject/notation/blob/main/.goreleaser.yml

However, `notation-go` is a golang package. Releasing a golang package is as simple as tag a commit, and that's it. After tagging, you may want to edit the release note.

2022-06-29 00:46 UTC, dtzar commented
@shizhMSFT - you're right which has made me reconsider using this to release the APIs.  It would be nice to automate release notes.  There are numerous approaches (i.e. .[GitHub action release-drafter](https://github.com/marketplace/actions/release-drafter) or the [make / shell script route](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/6108211bf3cc6dc1934699f95d2fa918993b9610/Makefile#L521-L603))  

Abandoning/closing this PR out.

Do you or anyone else have any preferences here?

2022-06-29 00:46 UTC, closed without merging