Migrate to codecov.io
notaryproject/notation-go pull request #92
Opened 2022-07-26 08:11 UTC by junczhuMSFT

Codecov Migrate Steps:

- [x] add coverage percent at .codecov
- [x] add codecov-action at build.yml (update with notation-core-go)
- [x] add badge at README.md

- [x] update make test with go test at makefile
- [x] update .gitignore / rmv .cover/ .test/ add coverage.txt

- [x] del shell/test.sh
- [x] del origin upload coverage report from build.yml (update with notation-core-go)

Signed-off-by: Juncheng Zhu <junczhu@microsoft.com>

2022-07-27 03:50 UTC, shizhMSFT approved these changes
LGTM

2022-07-27 16:37 UTC, priteshbandi approved these changes
LGTM

2022-07-28 01:39 UTC, shizhMSFT requested changes

2022-07-28 01:39 UTC, shizhMSFT commented on README.md
> +[![codecov](https://codecov.io/gh/notatryproject/notation-go/branch/main/graph/badge.svg)](https://codecov.io/gh/notatryproject/notation-go)
```suggestion
[![codecov](https://codecov.io/gh/notary/notation-go/branch/main/graph/badge.svg)](https://codecov.io/gh/notaryproject/notation-go)
```

2022-07-28 02:03 UTC, junczhuMSFT commented on README.md
> +[![codecov](https://codecov.io/gh/notatryproject/notation-go/branch/main/graph/badge.svg)](https://codecov.io/gh/notatryproject/notation-go)
README updated

2022-07-28 04:47 UTC, shizhMSFT approved these changes
LGTM

2022-07-28 04:50 UTC, merged